#!/bin/bash

DAYS=10

for arg
do
    OUT=`seafile-share-link -e=$DAYS "$arg" 2>&1`
    if [ "$?" -eq 0 ]
    then
	OUT=$(sed 's#\(http[^  ]*\)#\n<a href="&">&</a>#' <<< $OUT)
        OUT="${OUT}\n(valid for $DAYS days)"
	zenity --info --title="Share link" --width 350 --text="$OUT"
    else
	zenity --error --title="Share link" --text="$OUT"
    fi
done
