#!/bin/bash

for arg
do
    OUT=`seafile-share-link "$arg" 2>&1`
    if [ "$?" -eq 0 ] || [ "$?" -eq 1 ]
    then
        OUT=$(sed 's#\(http[^  ]*\)#\n<a href="&">&</a>#' <<< $OUT)
        zenity --info --title="Share link" --width 350 --text="$OUT"
    else
        zenity --error --title="Share link" --text="$OUT"
    fi
done
